# ==============================================================
# CI with GitHub Actions
# ==============================================================

name: Build

on:
  - push
  - pull_request

env:
  default-python: 3.9

jobs:
  testing:
    uses: quatrope/ProperImage/.github/workflows/testing.yml@d10f7d57dd03f66e74a7f0a3e7b01856cf0a9083

