# ==============================================================
# CI with GitHub Actions
# ==============================================================

name: Build

on:
  - push
  - pull_request

env:
  default-python: 3.9

jobs:
  testing:
    uses: quatrope/ProperImage/.github/workflows/testing.yml@1391802